eosnetworkfoundation/silkworm

- core/silkworm/state/delta.cpp
- node/silkworm/stagedsync/stage_hashstate.cpp
this fixes a stabiliby issue in write_changes_from_changed_addresses when changed_addresses is empty.
https://github.com/eosnetworkfoundation/eos-evm/issues/535
> fix silkworm stability issue

- node/silkworm/stagedsync/stage_history_index.cpp
Find will cause issue if we have empty blocks, which is indeed the case.
Silkworm part of the fix for https://github.com/eosnetworkfoundation/eos-evm/issues/551
> Use lower_bound instead of find to locate changeset

- silkworm/core/common/util.hpp
- silkworm/core/types/transaction.cpp
- silkworm/node/stagedsync/stages/stage_senders.cpp
support https://github.com/eosnetworkfoundation/eos-evm/pull/634
> Allow recover regular evm addresses from s if r is 0

- silkworm/core/execution/evm.cpp
Silkworm part for the solution of https://github.com/eosnetworkfoundation/eos-evm-node/issues/48
Be careful not to include this if we do not want to include this fix in the hotfix for https://github.com/eosnetworkfoundation/eos-evm-node/issues/51
> Generate trace for calls to pre_compile addresses properly.

- silkworm/core/execution/evm.cpp
Forwarding https://github.com/eosnetworkfoundation/silkworm/pull/63 to the `master` branch.
This PR replaces https://github.com/eosnetworkfoundation/silkworm/pull/64.
> Forwarding to master: Generate trace for calls to pre_compile addresses properly

- silkworm/silkrpc/core/evm_trace.cpp
For https://github.com/eosnetworkfoundation/eos-evm-node/issues/88
We can manually path the explorer rpc machine with this fix first. Do not merge right away.
We can decide whether this should be part of 0.6.3 or 0.7
> [0.1] Fix how the trace quirk is applied.

- silkworm/silkrpc/json/types.hpp
- silkworm/silkrpc/json/types_test.cpp
Fix for
https://github.com/eosnetworkfoundation/eos-evm-node/issues/123
Note that though the fix is using the format specified in EIP1898, the "requireCanonical" field will be ignored for now as it's much more complicated to support. 
We shall use separate issue to track that if necessary.
> Add support for input BlockNumOrHash using json object in params of eth_call and some other calls

- silkworm/silkrpc/commands/eth_api.cpp
- silkworm/silkrpc/core/blocks.cpp
issue https://github.com/eosnetworkfoundation/eos-evm-node/issues/70
- ensure block returned in "getblockbynumber" has passed the "kFinish" state (otherwise it returns empty object which indicates blocks not exist), so that logs will always be available for the same block.
- eth_blockNumber returns the max block number in the kFinish state instead of kExecution state.
> ensure blocks returned has passed finished state

- silkworm/node/db/access_layer.cpp
- silkworm/node/db/access_layer.hpp
- silkworm/node/db/access_layer_test.cpp
- silkworm/node/db/tables.hpp
- silkworm/node/db/util.cpp
- silkworm/node/db/util.hpp
Resolve #116 
The table names or some may change. 
And we may want to move some of the code to separate files
> Add a table in db to hold runtime state info.

- CMakeLists.txt
- cmake/conan.cmake
- cmake/profiles/linux_arm_gcc_11_debug
- cmake/profiles/linux_arm_gcc_11_release
- silkworm/silkrpc/commands/ots_api.cpp
Resolve #128 
Allow conan to proerly compile on linux on arm
Part of https://github.com/eosnetworkfoundation/eos-evm-node/issues/52
> Support arm in linux

- silkworm/silkrpc/common/util.cpp
- silkworm/silkrpc/common/util_test.cpp
> fix is_replay_protected

- eosevm/version.hpp
- silkworm/core/execution/processor.cpp
- silkworm/core/execution/processor_test.cpp
> [1.0] Change gas refund for eos_evm_version >= 2

- silkworm/core/execution/evm.cpp
- silkworm/core/execution/evm.hpp
- silkworm/core/execution/evm_test.cpp
- silkworm/core/execution/processor_test.cpp
> [1.0] Change EVM::account_exists to return true for reserved addresses if eos_evm_version >= 1

- silkworm/node/db/mdbx.cpp
- silkworm/silkrpc/daemon.cpp
- silkworm/silkrpc/settings.hpp
Fix mdbx related issues
Mainly for the db size issue.
> [0.2] Cherry pick mdbx related fixes

- silkworm/silkrpc/commands/eth_api.cpp
- silkworm/silkrpc/commands/trace_api.cpp
- silkworm/silkrpc/core/call_many.cpp
- silkworm/silkrpc/core/call_many.hpp
- silkworm/silkrpc/core/estimate_gas_oracle.cpp
- silkworm/silkrpc/core/evm_debug.cpp
- silkworm/silkrpc/core/evm_executor.cpp
- silkworm/silkrpc/core/evm_executor.hpp
- silkworm/silkrpc/core/evm_executor_test.cpp
- silkworm/silkrpc/core/evm_trace.cpp
- silkworm/silkrpc/core/evm_trace.hpp
- silkworm/silkrpc/core/gas_parameters.cpp
- silkworm/silkrpc/core/gas_parameters.hpp
> [1.0.5] Refactor EVMExecutor::call

- LICENSE
Forwards PRs https://github.com/eosnetworkfoundation/silkworm/pull/209 and https://github.com/eosnetworkfoundation/silkworm/pull/210 to `master`.
> [1.0.6 -> master] Change to BSL licensing scheme

- silkworm/node/stagedsync/stages/stage_senders.cpp
https://github.com/eosnetworkfoundation/eos-evm-node/issues/258
> improve the recover performance by re-using the secpk1 context

- silkworm/silkrpc/core/evm_trace.cpp
- silkworm/silkrpc/core/evm_trace_test.cpp
> [1.0] Do not rely on exists to determine if it's create

- CMakeLists.txt
- silkworm/silkrpc/core/evm_trace.cpp
- silkworm/silkrpc/core/evm_trace_test.cpp
> [1.0 -> master] Do not rely on exists to determine if it's create in traces

- CMakeLists.txt
- silkworm/silkrpc/commands/eth_api.cpp
> [1.0->main] call_eth no longer need the set the max_fee_per_gas

- silkworm/silkrpc/commands/rpc_api_table.cpp
Revert "Merge pull request #230 from eosnetworkfoundation/yarkin/expose_eth_gasPrice"
This reverts commit 7bf393c3314b1fd5280abbc31d12b499a55ec199, reversing changes made to c87ecea60b3fd48c32bc2bcaedd4aba70fc3db62.
The fix needs to be merged into 1.0 first
> Revert improper merge.
