eosnetworkfoundation/silkworm

core/silkworm/state/delta.cpp, node/silkworm/stagedsync/stage_hashstate.cpp
Brings #32 forward to `eos-evm-main` branch.
Part of [#535](https://github.com/eosnetworkfoundation/eos-evm/issues/535).
=> [eos-evm-0.4 -> eos-evm-main] fix silkworm stability issue

core/silkworm/execution/evm.cpp
https://github.com/eosnetworkfoundation/eos-evm/issues/455
=> Kayan no advanced executor

silkworm/silkrpc/http/server.cpp
closes eosnetworkfoundation/eos-evm#548
=> Fix build with gcc12

silkworm/silkrpc/common/util.hpp, silkworm/silkrpc/http/request_handler.cpp, silkworm/silkrpc/json/call.cpp, silkworm/silkrpc/json/call.hpp, silkworm/silkrpc/json/log.cpp, silkworm/silkrpc/json/log.hpp, silkworm/silkrpc/json/types.cpp
=> Adapt make_glaze_json_content to handle different request id types

silkworm/silkrpc/commands/eth_api.cpp, silkworm/silkrpc/ethdb/bitmap.cpp, silkworm/silkrpc/ethdb/bitmap.hpp
Ported from
https://github.com/eosnetworkfoundation/eos-evm/commit/f7ff85152b6867c7135857575ce9c4c03000cfdd
=> Properly read address/topic index bitmap from db to serve eth_getLogs calls

silkworm/core/execution/evm.cpp, silkworm/silkrpc/commands/eth_api.cpp, silkworm/silkrpc/ethdb/bitmap.cpp, silkworm/silkrpc/ethdb/bitmap.hpp
Forward PRs https://github.com/eosnetworkfoundation/silkworm/pull/62 and https://github.com/eosnetworkfoundation/silkworm/pull/63 to the `master` branch.
=> Forward PRs #62 and #63 to master

silkworm/silkrpc/json/transaction_test.cpp
Resolve #42 
comment: I'm not sure whether we should make "from" equal to all zeros in this case. but it may be better not to change the existing core logic
=> fix serialize empty txn test

silkworm/node/stagedsync/stages/stage_senders.cpp
https://github.com/erigontech/silkworm/pull/1488
=> node: speed up parallel recover in Senders stage for small spans

silkworm/silkrpc/core/evm_trace.cpp, silkworm/silkrpc/json/call.cpp, silkworm/silkrpc/json/call_test.cpp
=> [0.1->main] Fix mining rewards; Supporting input field in eth_call;

silkworm/silkrpc/commands/eth_api.cpp
=> [0.1] Handle extra block tag parameter in eth_estimateGas

cmd/common/rpcdaemon_options.cpp, silkworm/silkrpc/commands/rpc_api.hpp, silkworm/silkrpc/commands/rpc_api_quirk.hpp, silkworm/silkrpc/commands/trace_api.cpp, silkworm/silkrpc/commands/trace_api.hpp, silkworm/silkrpc/core/evm_trace.cpp, silkworm/silkrpc/core/evm_trace.hpp, silkworm/silkrpc/daemon.cpp, silkworm/silkrpc/daemon.hpp, silkworm/silkrpc/http/server.cpp, silkworm/silkrpc/http/server.hpp, silkworm/silkrpc/settings.hpp
For https://github.com/eosnetworkfoundation/eos-evm-node/issues/88
Missing part:
In node, rpc_plugin needs to pass flag to DaemonSettings during intialization.
=> [0.1] A possible approach to add a trace quirk mode option

silkworm/silkrpc/commands/eth_api.cpp
=> [0.1] Let eth_call properly handle block_number_or_hash string.

cmd/common/rpcdaemon_options.cpp, silkworm/silkrpc/commands/eth_api.cpp, silkworm/silkrpc/commands/rpc_api.hpp, silkworm/silkrpc/commands/rpc_api_quirk.hpp, silkworm/silkrpc/commands/trace_api.cpp, silkworm/silkrpc/commands/trace_api.hpp, silkworm/silkrpc/commands/trace_api_test.cpp, silkworm/silkrpc/core/evm_trace.cpp, silkworm/silkrpc/core/evm_trace.hpp, silkworm/silkrpc/daemon.cpp, silkworm/silkrpc/daemon.hpp, silkworm/silkrpc/http/server.cpp, silkworm/silkrpc/http/server.hpp, silkworm/silkrpc/settings.hpp
resolve #84 
and https://github.com/eosnetworkfoundation/eos-evm-node/issues/88
=> [0.1->master] Merge in fixes for trace quirk and eth_call hash fix

silkworm/silkrpc/core/evm_trace.cpp
See https://github.com/eosnetworkfoundation/eos-evm-node/issues/120
=> [0.1->master] Fix how the quirk mode handle trace

silkworm/silkrpc/core/estimate_gas_oracle.cpp, silkworm/silkrpc/core/evm_executor.cpp, silkworm/silkrpc/core/evm_executor.hpp
=> [0.1 -> master] Extend EVMExecutor to have full and a partial reset of the internal state

silkworm/core/types/transaction_test.cpp
=> Add tests for special signatures

silkworm/silkrpc/commands/eth_api.cpp, silkworm/silkrpc/commands/parity_api.cpp
=> Let more API use blockNumberOrHash.

silkworm/node/db/access_layer.cpp, silkworm/node/db/access_layer.hpp, silkworm/node/db/access_layer_test.cpp
=> Function argument list tweak for runtime_state db functions

silkworm/node/db/mdbx.cpp, silkworm/silkrpc/daemon.cpp, silkworm/silkrpc/settings.hpp
=> Fix mdbx related issues

eosevm/block_mapping.hpp
silkworm changes for https://github.com/eosnetworkfoundation/eos-evm-contract/issues/697
=> add base_fee_per_gas in prepare header

eosevm/version.hpp
changes for https://github.com/eosnetworkfoundation/eos-evm-contract/issues/695
=> eosevm version 1 to evmc london

eosevm/consensus_parameters.cpp, silkworm/node/db/access_layer_test.cpp
=> [1.0 -> master] Fix ConsensusParameters::decode

silkworm/silkrpc/core/evm_executor.cpp
https://github.com/eosnetworkfoundation/eos-evm-node/issues/243
=> [1.0] fix estimategas

eosevm/version.hpp, silkworm/core/execution/processor.cpp, silkworm/core/execution/processor_test.cpp
=> [1.0 -> main] Change gas refund for eos_evm_version >= 2

silkworm/core/execution/evm.cpp, silkworm/core/execution/evm.hpp, silkworm/core/execution/evm_test.cpp, silkworm/core/execution/processor_test.cpp
=> [1.0 -> master] Change EVM::account_exists to return true for reserved addresses if eos_evm_version >= 1

CMakeLists.txt
=> [1.0] Bump 1.0.2 version

CMakeLists.txt
=> [1.0 -> master] Bump 1.0.2 version

silkworm/core/chain/config.cpp, silkworm/core/chain/config.hpp, silkworm/core/chain/config_test.cpp
Resolves #175 
new implementation will save around 2.5KB stack size
=> support any chain_id

silkworm/silkrpc/core/estimate_gas_oracle.hpp, silkworm/silkrpc/core/estimate_gas_oracle_test.cpp
=> [1.0] Gas Estimator: change kGasCap to 100M

silkworm/silkrpc/core/estimate_gas_oracle.hpp, silkworm/silkrpc/core/estimate_gas_oracle_test.cpp
=> [1.0 -> master] Gas Estimator: change kGasCap to 100M

silkworm/silkrpc/commands/eth_api.cpp
=> [1.0] Fix eth_call when evm_version>0

CMakeLists.txt
=> [1.0] Bump 1.0.4 version

silkworm/silkrpc/commands/eth_api.cpp
=> [1.0 -> master] Fix eth_call when evm_version>0 

CMakeLists.txt
=> [1.0 -> master] Bump 1.0.4 version

silkworm/silkrpc/commands/eth_api.cpp
=> [1.0] call_eth no longer need the set the max_fee_per_gas

silkworm/silkrpc/commands/rpc_api_table.cpp
=> [1.0] Enable eth_gasPrice

silkworm/silkrpc/commands/rpc_api_table.cpp
=> [1.0->master] Expose eth_gasPrice

silkworm/core/protocol/validation.cpp, silkworm/node/stagedsync/stages/stage_senders.cpp
=> [1.0] Allow higher s value in signature validation

silkworm/silkrpc/core/evm_executor.cpp, silkworm/silkrpc/core/gas_parameters.cpp
Will fix bugs https://github.com/eosnetworkfoundation/eos-evm-node/issues/360 and https://github.com/eosnetworkfoundation/eos-evm-node/issues/361 when silkworm changes brought into eos-evm-node.
=> EVMExecutor: Fix inclusion_price calculation and gas_prices_index retrieval
